In [5]:
import torch
torch.__version__, torch.cuda.is_available()

('2.5.1+cu124', True)

In [6]:
import numpy as np

In [51]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

In [9]:
a, b = np.random.randn(2, 3), np.random.randn(3)
a

array([[ 0.90865721,  1.23491433, -0.17781023],
       [-0.07704893,  0.61656516,  1.3320255 ]])

In [10]:
b

array([-0.58758869, -0.09955587, -0.44303561])

In [27]:
at, bt = torch.randn(3), torch.ones(3)
at, bt

(tensor([0.5922, 1.3665, 1.2619]), tensor([1., 1., 1.]))

In [28]:
a*b

array([[-0.5339167 , -0.12294297,  0.07877626],
       [ 0.04527308, -0.06138268, -0.59013473]])

In [29]:
at*bt

tensor([0.5922, 1.3665, 1.2619])

In [30]:
np.dot(a, b)

array([-0.5780834 , -0.60624433])

In [31]:
torch.dot(at, bt)

tensor(3.2205)

In [33]:
ct = torch.randint(255, (3,))
ct

tensor([115, 102, 148])

In [34]:
torch.dot(at, ct)

RuntimeError: dot : expected both vectors to have same dtype, but found Float and Long

In [36]:
c = np.random.randint(1, 255, (3,))
c

array([ 78, 250,   1])

In [40]:
np.dot(a, c)

array([379.42603504, 149.46349826])

In [58]:
m1 = torch.randn((3,2))
m2 = torch.randn((2,3))
torch.matmul(m2, m1)

tensor([[-0.4091,  0.8136],
        [-0.9587,  0.2512]])

In [59]:
m1.to('cuda').device, m1.device

(device(type='cuda', index=0), device(type='cpu'))

In [60]:
torch.matmul(m1.to('cuda'), m1)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

In [62]:
torch.matmul(m1.to(device), m2.to(device)).cpu()

tensor([[ 0.0756, -2.8016, -5.1407],
        [-0.1326, -0.9905, -1.5915],
        [ 0.1791,  0.5627,  0.7570]])

In [69]:
big_arr = np.ones((3,3)).astype('float32')
print(torch.tensor(big_arr, requires_grad=True))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [80]:
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
x1 = torch.tensor([[1.]],requires_grad=True)
print(x.dtype)
out = x1.item()
print(out)
out.backward()
x.grad

torch.float32
1.0


AttributeError: 'float' object has no attribute 'backward'

In [72]:
x==1

tensor([[ True, False],
        [ True,  True]])

In [101]:
from torch.nn import Module, Linear, ReLU, Softmax, ModuleList, Sequential

In [102]:
class MyNN(Module):

    def __init__(self):
        super().__init__()
        self.layers = ModuleList([
            Linear(in_features=2, out_features=3),
            ReLU(),
            Linear(in_features=3, out_features=2),
            ReLU(),
            Linear(in_features=2, out_features=2),
        ])


    def forward(self, x):
        for layer in self.layers:
            x = layer(x)
        return Softmax(dim=-1)(x)


nn = MyNN()
res = nn(torch.tensor([1.,1.]))
res

tensor([0.5611, 0.4389], grad_fn=<SoftmaxBackward0>)

In [103]:
sq = Sequential(
    Linear(in_features=2, out_features=3),
    ReLU(),
    Linear(in_features=3, out_features=2),
    Softmax(dim=-1)
)
res = sq(torch.tensor([1.,1.]))
res

tensor([0.2237, 0.7763], grad_fn=<SoftmaxBackward0>)